---

  - name: 3.1.1 Ensure IP forwarding is disabled (Scored)
    sysctl:
      name: net.ipv4.ip_forward
      value: '{{net_ipv4_ip_forward}}'
      state: present
      reload: yes
    tags:
      - section3
      - section3.1
      - section3.1.1

  - name: 3.1.2 Ensure packet redirect sending is disabled (Scored)
    sysctl:
      name: net.ipv4.conf.all.send_redirects
      value: 0
      state: present
      reload: yes
    tags:
      - section3
      - section3.1
      - section3.1.2
      
  - name: 3.1.2 Ensure packet redirect sending is disabled (Scored) Part 2
    sysctl:
      name: net.ipv4.conf.default.send_redirects
      value: 0
      state: present
      reload: yes
    tags:
      - section3
      - section3.1
      - section3.1.2
